
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int PLUS = 5;
  public static final int INT = 21;
  public static final int RPAREN = 12;
  public static final int CALL = 10;
  public static final int SEMI = 4;
  public static final int WHILE = 3;
  public static final int END = 18;
  public static final int FUNCTION = 17;
  public static final int LPAREN = 11;
  public static final int GT = 9;
  public static final int ID = 20;
  public static final int DO = 2;
  public static final int ASSIGNS = 13;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int FINISH = 19;
  public static final int MINUS = 6;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int START = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DO",
  "WHILE",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "GT",
  "CALL",
  "LPAREN",
  "RPAREN",
  "ASSIGNS",
  "PRINT",
  "COMMA",
  "START",
  "FUNCTION",
  "END",
  "FINISH",
  "ID",
  "INT"
  };
}

